version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    allow:
      - dependency-name: '*'
      - dependency-type: all
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
    commit-message:
      prefix: chore
      prefix-development: chore
      include: scope
    open-pull-requests-limit: 10
